### ISSUE TITLE
Share ics file

### ISSUE THREAD

**Issue by steveny909** [dartclub/ical#11]
Sorry for the simple question but I'm new to Flutter...how can I take the ics file generated and send via text or email using flutter package like share?  Share.shareFiles uses a local path but I don't understand how I would save ics to path.

**Comment by lukas-h** [comment]
https://flutter.dev/docs/cookbook/persistence/reading-writing-files#1-find-the-correct-local-path

here you go if you want to write it in your app's folder

**Comment by steveny909** [comment]
Thank you.  I didn't appreciate that cal.serialize() just creates a file.   And thanks for maintaining a great little package.
