### ISSUE TITLE
depends on intl ^0.16.0 (Flutter 2.x support)

### ISSUE THREAD

**Issue by mauriceraguseinit** [dartclub/ical#14]
Hi,

in Flutter 2.x.x intl ^0.17.0 is needed. ical  0.1.3 needs intl ^0.16.0 

can you update the dependencies?

**Comment by steveny909** [comment]
Thank you @lukas-h for updating a couple of days ago.   Without a new ical version though, my ical 0.1.3 still thinks it requires intl 0.16.0.   Can someone tell me how to get a new version of 0.1.3 with the updated pubspec.yaml for intl 0.17.0?

**Comment by lukas-h** [comment]
I updated all the dependencies to the latest version alongside support for null-safety. All available in newly shipped version `0.2.0`
